insert into Instructor (FirstName, LastName, Email, Password) values ('Henriette', 'Challenger', 'HenrietteChallenger@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Bartholemy', 'Rosendall', 'BartholemyRosendall@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Celka', 'Starsmore', 'CelkaStarsmore@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Bessy', 'Iacopini', 'BessyIacopini@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Sherline', 'Ivatt', 'SherlineIvatt@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Darrin', 'Bunney', 'DarrinBunney@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Ardis', 'Della Scala', 'ArdisDella Scala@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Hillary', 'Lukash', 'HillaryLukash@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Moshe', 'McNickle', 'MosheMcNickle@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Hester', 'O'' Finan', 'HesterO'' Finan@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Kristen', 'Treagus', 'KristenTreagus@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Shell', 'Swadlen', 'ShellSwadlen@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Coriss', 'Spykings', 'CorissSpykings@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Buddie', 'Brimicombe', 'BuddieBrimicombe@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Lynea', 'Starking', 'LyneaStarking@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Stormy', 'Stitle', 'StormyStitle@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Cordy', 'Lusher', 'CordyLusher@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Padraig', 'Spurnier', 'PadraigSpurnier@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Zebulen', 'Cosins', 'ZebulenCosins@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Rosemary', 'Winfindine', 'RosemaryWinfindine@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Dennie', 'Brehat', 'DennieBrehat@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Lucien', 'Camerati', 'LucienCamerati@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Brenda', 'Filyashin', 'BrendaFilyashin@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Meryl', 'Grishakin', 'MerylGrishakin@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
insert into Instructor (FirstName, LastName, Email, Password) values ('Querida', 'Haggie', 'QueridaHaggie@lms.edu', '$2a$10$wPwOetnrPsyIsGRVPJ0U1uHAAgT0/Hdcpd2CptOQ.MQwxGxlsjs6K');
